### ISSUE TITLE
Setting Times in Due date subtracts 4 hours???

### ISSUE THREAD

**Issue by aananiadis** [j6k4m8/meteor-todo#3]

**Comment by j6k4m8** [comment]
My suspicion is that this is a timezone issue, since we're GMT-4 right now

**[EDIT]** Confirmed. The reason for this not happening with the buttons is that they take `now()` and add time, whereas setting it via text is "absolute." 

If you're running this on a server, make sure your server TZ is set correctly... and if that still doesn't help, then yeah this is buggy
